# Configuration for development teams
language: "en-US"

reviews:
  profile: "assertive"
  high_level_summary: true
  early_access: true
  auto_review:
    enabled: true
    drafts: false
  ignore_title_keywords:
    - "wip"
    - "draft"
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursorrules"
      - "**/CODING_STANDARDS.md"
