# Gemini Code Assist configuration
# Conservative, security‑first defaults suitable for web/AI/health apps.

have_fun: false # keep PR output professional

code_review:
disable: false
# Only surface actionable issues; raise severity for production repos
comment_severity_threshold: MEDIUM # LOW|MEDIUM|HIGH|CRITICAL
# Use -1 for unlimited. For busy repos, cap to avoid noise.
max_review_comments: 200

pull_request_opened:
help: false # avoid boilerplate help spam
summary: true # always request a PR summary
code_review: true

# Files and directories Gemini should skip in reviews and chats.
# Add paths that are generated, vendored, or too noisy.
ignore_patterns:
# Node / React / Next.js
- '**/node_modules/**'
- '**/.next/**'
- '**/out/**'
- '**/dist/**'
- '**/build/**'
- '**/coverage/**'
- '**/*.min.js'
- '**/*.map'

# Flutter / Dart
- '**/.dart_tool/**'
- '**/build/**'
- '**/android/**/build/**'
- '**/ios/**/Pods/**'

# Python / Django
- '**/.venv/**'
- '**/venv/**'
- '**/__pycache__/**'
- '**/*.pyc'
- '**/staticfiles/**'
- '**/media/**'
# If migrations are large/noisy, ignore autogenerated ones
- '**/*migrations/**'

# Docs & assets (optional)
- '**/public/assets/**'
- '**/static/**'
- '**/*.svg'
- '**/*.png'
- '**/*.jpg'
- '**/*.jpeg'
- '**/*.gif'

# Generated/open‑api/specs (optional)
- '**/openapi_generated/**'
- '**/*schema.graphql*'

# Secrets & local env (NEVER commit secrets!)
- '**/.env*'
- '**/secrets/**'

# Advanced presets (optional): per‑language or path‑scoped overrides
# Uncomment and customize if you want different thresholds for specific paths.
# path_overrides:
# - path: 'backend/**'
# comment_severity_threshold: HIGH
# - path: 'frontend/**'
# max_review_comments: 120
